window.StreamDeckShortcutsPreviewFixture = {
  folders: ['All', 'Workflows', 'Writing', 'Media', 'Home', 'Utilities', 'Unsorted'],
  shortcutCatalog: [
    { name: 'Daily Briefing', folder: 'Workflows' },
    { name: 'Start Focus Session', folder: 'Workflows' },
    { name: 'Create Project Summary', folder: 'Workflows' },
    { name: 'Draft Follow-up Email', folder: 'Writing' },
    { name: 'Translate Selected Text', folder: 'Writing' },
    { name: 'Summarize This Article', folder: 'Writing' },
    { name: 'Play Focus Playlist', folder: 'Media' },
    { name: 'Resize Image for Sharing', folder: 'Media' },
    { name: 'Create Video Chapters', folder: 'Media' },
    { name: 'Set Desk Lights', folder: 'Home' },
    { name: 'Start Kitchen Timer', folder: 'Home' },
    { name: 'Good Night', folder: 'Home' },
    { name: 'Open Password Manager', folder: 'Utilities' },
    { name: 'Clear Downloads Folder', folder: 'Utilities' },
    { name: 'Copy Current Window Title', folder: 'Utilities' },
    { name: 'Plan a Trip to Montréal', folder: 'Unsorted' },
    { name: 'Résumé de la réunion', folder: 'Unsorted' },
    { name: '日本語のテスト', folder: 'Unsorted' },
    { name: 'Очень длинное название ярлыка для проверки усечения', folder: 'Unsorted' },
  ],
};
